# Generated by Django 4.2.3 on 2024-10-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='option',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ques',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='mark',
            new_name='grade',
        ),
    ]
